[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
ignore = [
    # The Leptonic build writes these files. Not ignoring them could lead to infinite rebuilds when using `trunk serve`.
    "./style/leptonic"
]

[[hooks]]
stage = "post_build"
command = "cargo"
command_arguments = ["run", "--manifest-path", "./xtasks/Cargo.toml", "post_build"]
