[build]
public_url = "./"

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
ignore = [
    # The Leptonic build writes these files. Not ignoring them could lead to infinite rebuilds when using `trunk serve`.
    "./style/leptonic"
]
