[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
ignore = [
    # files not impacting the app build
    "README.md",
]

[[hooks]]
stage = "post_build"
command = "cargo"
command_arguments = ["run", "--manifest-path", "./xtasks/Cargo.toml", "post_build"]
