name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@1.88
      with:
        targets: wasm32-unknown-unknown

    # get prebuilt trunk instead of spending 5min+ of CI time
    - uses: jetli/trunk-action@v0.4.0
      #with:
      #  version: 'v0.18.4'

    - name: Build
      run: trunk build --verbose --release --public-url "./"
    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
      with:
        name: static-webapp
        path: ./dist
